version: '3'

services:
  mysql:
    image: 'mysql:8.0'
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ROOT_PASSWORD=Hung@123@16145464
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=hukhho
      - MYSQL_PASSWORD=Hung@123
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pexamplepassword" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork

  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mydatabase
      - SPRING_DATASOURCE_USERNAME=hukhho
      - SPRING_DATASOURCE_PASSWORD=Hung@123
    networks:
      - mynetwork

volumes:
  mysql-data:
    driver: local

networks:
  mynetwork:
